type state

external newstate: unit -> state = "lua__newstate"
external pushnil: state -> unit = "lua__pushnil"
external pushboolean: state -> bool -> unit = "lua__pushboolean"
external pushnumber: state -> float -> unit = "lua__pushnumber"
external pushinteger: state -> int -> unit = "lua__pushinteger"
external pushstring: state -> string -> unit = "lua__pushstring"
external checkstack: state -> int -> bool = "lua__checkstack"
external isnumber: state -> int -> bool = "lua__isnumber"
external isstring: state -> int -> bool = "lua__isstring"
external toboolean: state -> int -> bool = "lua__toboolean"
external tonumber: state -> int -> float = "lua__tonumber"
external tointeger: state -> int -> int = "lua__tointeger"
external tostring: state -> int -> string = "lua__tostring"
external pushfunction: state -> (state -> int) -> unit = "lua__pushfunction"
external pcall: state -> int -> unit = "lua__pcall"
external pop: state -> int -> unit = "lua__pop"
external setglobal: state -> string -> unit = "lua__setglobal"
external getglobal: state -> string -> unit = "lua__getglobal"
external close: state -> unit = "lua__close"
external loadstring: state -> string -> unit = "lua__loadstring"
